### ISSUE TITLE
Would you have any interest posting this to the FreeCAD Path subforum?

### ISSUE THREAD

**Issue by luzpaz** [Metalab/freecad-cnc-postprocessor#1]
I'm sure the FreeCAD Path community will appreciate the effort!  
https://forum.freecad.org/viewforum.php?style=5&f=15

**Comment by luto** [comment]
The changes here are very specific to our machine. Which parts do you think would be interesting for the wider community?

**Comment by luzpaz** [comment]
Maybe explaining why you needed to customize and perhaps sharing a little more info about the machine itself?

**Comment by luto** [comment]
https://forum.freecad.org/viewtopic.php?style=5&t=75852

Still in moderation queue, though.
